-- Genera tablas iniciales
-- App: JEE_INSCRIPCIONES
-- Autor: RRHG
-- Fecha: 11/septiembre/2025

-- TBL_CURSO
CREATE OR REPLACE TABLE TBL_CURSO (
    id_curso INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1)
        NOT NULL PRIMARY KEY
    ,descripcion VARCHAR -- Nombre del curso
    ,duracion INTEGER -- En meses
    ,precio DOUBLE -- USD
);


-- TBL_FORMA_PAGO
CREATE OR REPLACE TABLE TBL_FORMA_PAGO (
    id_forma_pago INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1)
        NOT NULL PRIMARY KEY
    ,descripcion VARCHAR
    ,recargo DOUBLE
);

/*
Recordatorio: sintaxis para agregar constraint FK (Oracle SQL):
ALTER TABLE child_table_name
ADD CONSTRAINT constraint_name
FOREIGN KEY (child_column_name)
REFERENCES parent_table_name (parent_column_name);
*/

-- TBL_CURSO_FORMA_PAGO (tabla relacional)
CREATE OR REPLACE TABLE TBL_CURSO_FORMA_PAGO (
    id_curso INTEGER -- FK
    ,id_forma_pago INTEGER -- FK
);

ALTER TABLE TBL_CURSO_FORMA_PAGO
ADD CONSTRAINT fk_id_curso
FOREIGN KEY (id_curso)
REFERENCES tbl_curso (id_curso)
;

ALTER TABLE TBL_CURSO_FORMA_PAGO
ADD CONSTRAINT fk_id_forma_pago
FOREIGN KEY (id_forma_pago)
REFERENCES tbl_forma_pago (id_forma_pago)
;

-- PK compuesta por las 2 FKs:
ALTER TABLE TBL_CURSO_FORMA_PAGO
ADD CONSTRAINT pk_curso_forma_pago
PRIMARY KEY (id_curso, id_forma_pago)


-- TBL_ALUMNO
CREATE OR REPLACE TABLE TBL_ALUMNO (
    id_alumno INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY
    ,nombre VARCHAR
    ,telefono VARCHAR
);


--TBL_INSCRIPCION
CREATE OR REPLACE TABLE TBL_INSCRIPCION (
    id_inscripcion INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY
    ,id_alumno INTEGER -- FK
    ,id_curso INTEGER -- FK
    ,fecha DATE
);

ALTER TABLE TBL_INSCRIPCION
ADD CONSTRAINT fk_id_alumno
FOREIGN KEY (id_alumno)
REFERENCES tbl_alumno (id_alumno)
;

ALTER TABLE TBL_INSCRIPCION
ADD CONSTRAINT fk_id_curso
FOREIGN KEY (id_curso)
REFERENCES tbl_curso (id_curso)
;
